[package]
name = "purple"
version = "0.0.1"
license = "GPL-3.0"
publish = false

[workspace]

[dependencies]
clap = "2.32.0"
unwrap = "1.2.0"
hex = "0.3.2"
itc = "0.1.2"
log = "0.4.0"
env_logger = "0.6.0"
parking_lot = "0.6"
tokio = "0.1.11"
futures = "0.1.25"
dirs = "1.0.4"
elastic-array = "0.10.0"
jsonrpc-core = "9.0.0"
jsonrpc-macros = "9.0.0"
hashdb = { git = "https://github.com/paritytech/parity-common" }
kvdb = { git = "https://github.com/paritytech/parity-common" }
kvdb-rocksdb = { git = "https://github.com/paritytech/parity-common" }
account = { path = "src/account" }
purple_vm = { path = "src/purple_vm" }
crypto = { path = "src/crypto" } 
jump = { path = "src/jump" }
events = { path = "src/events" }
consensus = { path = "src/consensus" }
persistence = { path = "src/persistence" }
network = { path = "src/network" }
transactions = { path = "src/transactions" }
chain = { path = "src/chain" }

[[bin]]
path = "src/purple/main.rs"
name = "purple"

[profile.release]
lto = true