[package]
name = "persistence"
version = "0.1.0"
authors = ["octavonce <octavonce@gmail.com>"]
publish = false

[dependencies]
hashdb = "0.3.0"
patricia-trie = "0.3.0"
elastic-array = "0.10.0"
rlp = "0.3.0"
parking_lot = "0.6"
kvdb = "0.1.0"
kvdb-rocksdb = "0.1.0"
crypto = { path = "../crypto" }

[dev-dependencies]
tempfile = "3.0.5"