[package]
name = "chain"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
elastic-array = "0.10.0"
byteorder = "1.2.7"
lru = "0.1.13"
rlp = "0.3.0"
parking_lot = "0.6"
crypto = { path = "../crypto" }
persistence = { path = "../persistence" }
bin-tools = { path = "../util/bin-tools/" }
hashdb = { git = "https://github.com/paritytech/parity-common" }
hashbrown = { git = "https://github.com/octavonce/hashbrown", features = ["serde", "rayon"] }